name: Filip's Blog
description: Marketing, Kendo and Mountain Biking
meta_description: "Marketing gari, Kendo master and all around nice guy"

markdown: redcarpet
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://filipkmn.github.io/'
google_analytics: 'UA-73151731-1'

# Details for the RSS feed generator
url:            'http://filipkmn.github.io'
author:         'Filip Komnenovic'
  featured_image: true
  facebook:     filip.kmn
  twitter:      filipkmn
  google_plus:  115361850116162945128
  fb_admins:      100007979086072
  fb_appid:       your facebook app id

#adde featured_image, facebook, twitter, google_plus, fb_admins, fb_appid
